## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild TestCalculadora/TestCalculadora.sln
  - nunit-console TestCalculadora/bin/Debug/TestCalculadora.dll
  
