## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
